# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, default='', max_length=255)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.CharField(blank=True, default='', max_length=255)),
                ('ttl', models.IntegerField(blank=True, default=3600)),
                ('mx_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('priority', models.SmallIntegerField(blank=True, default=255, null=True)),
                ('refresh', models.IntegerField(blank=True, default=28800, null=True)),
                ('retry', models.IntegerField(blank=True, default=14400, null=True)),
                ('expire', models.IntegerField(blank=True, default=86400, null=True)),
                ('minimum', models.IntegerField(blank=True, default=86400, null=True)),
                ('serial', models.BigIntegerField(blank=True, null=True)),
                ('resp_person', models.CharField(blank=True, default='admin', max_length=64, null=True)),
                ('primary_ns', models.CharField(blank=True, default='ns.admin.net', max_length=64, null=True)),
                ('reg_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('reg_time',),
            },
        ),
    ]
